CREATE TABLE expense (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    category_id CHAR(36) NOT NULL,
    subcategory_id CHAR(36) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    fees DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    description TEXT NULL,
    expense_datetime DATETIME NOT NULL,
    receipt_type ENUM('text', 'pdf', 'image') NOT NULL DEFAULT 'text',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_expense_user_id (user_id),
    INDEX idx_expense_category_id (category_id),
    INDEX idx_expense_subcategory_id (subcategory_id),
    INDEX idx_expense_datetime (expense_datetime),
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_expense_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT fk_expense_subcategory FOREIGN KEY (subcategory_id) REFERENCES subcategories(subcategory_id),
    CONSTRAINT chk_expense_amount CHECK (amount >= 0),
    CONSTRAINT chk_expense_fees CHECK (fees >= 0)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;